# Site settings
encoding: UTF-8
title: R-Spatialist
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Smart solutions for geospatial data processing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amsantac.co" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  amsantac
#pages_list:       
#  Blog: '/blog'
#  Feed: '/feed.xml'

# Build settings
#markdown: rdiscount
markdown: kramdown
kramdown:
  input: "GFM"
#  syntax_highlighter: "coderay"
#highlighter: rouge   # pygments
excerpt_separator: <!--more-->
