# Site settings
title: R-Spatialist
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Description edited in _config.yml for Google search result and feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amsantac.co" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  amsantac
#pages_list:       
#  Blog: '/blog'
#  Feed: '/feed.xml'

# Build settings
markdown: rdiscount
#markdown: kramdown
highlighter: pygments
